-- CONSTRAINTS

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_ACERVO_LIVROS
FOREIGN KEY(ID_LIVRO) REFERENCES ACERVO_LIVROS(IDLIVRO);

ALTER TABLE DEVOLUCAO ADD CONSTRAINT FK_DEVOLUCAO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE DEVOLUCAO ADD CONSTRAINT FK_DEVOLUCAO_ACER_LIVROS
FOREIGN KEY(ID_LIVRO) REFERENCES ACERVO_LIVROS(IDLIVRO);

ALTER TABLE RELATORIO ADD CONSTRAINT FK_RELATORIO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE RELATORIO ADD CONSTRAINT FK_RELATORIO_ACERVO_LIVROS
FOREIGN KEY(ID_LIVRO) REFERENCES ACERVO_LIVROS(IDLIVRO);

ALTER TABLE RELATORIO ADD CONSTRAINT FK_RELATORIO_EMPRESTIMO
FOREIGN KEY(ID_EMPRESTIMO) REFERENCES EMPRESTIMO(IDEMPRESTIMO);

ALTER TABLE MULTA ADD CONSTRAINT FK_MULTA_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE MULTA ADD CONSTRAINT FK_MULTA_ACERVO_LIVROS
FOREIGN KEY(ID_LIVRO) REFERENCES ACERVO_LIVROS(IDLIVRO);
