ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE CONTATO ADD CONSTRAINT FK_USUARIO_CONTATO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE USUARIO_LIVRO ADD CONSTRAINT FK_USUARIO_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE USUARIO_LIVRO ADD CONSTRAINT FK_LIVRO_ACERVO_LIVROS
FOREIGN KEY(ID_LIVRO) REFERENCES ACERVO_LIVROS(IDLIVRO);

ALTER TABLE EMPRESTIMO_DEVOLUCAO ADD CONSTRAINT FK_USUARIO_EMPRESTIMO_DEVOLUCAO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE EMPRESTIMO_DEVOLUCAO ADD CONSTRAINT FK_LIVRO_EMPRETIMO_DEVOLUCAO
FOREIGN KEY(ID_LIVRO) REFERENCES ACERVO_LIVROS(IDLIVRO);

ALTER TABLE MULTA ADD CONSTRAINT FK_MULTA_USUARIO
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);
