DELIMITER ?

CREATE PROCEDURE ADD_RELATORIO(P_DATA_DEVOLUCAO DATETIME)
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VID_USUARIO, VID_LIVRO, VID_EMPRESTIMO INT;

	DECLARE REG CURSOR FOR
		SELECT IDEMPRESTIMO, ID_USUARIO, ID_LIVRO
		FROM EMPRESTIMO;

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;
		REPEAT
			FETCH REG INTO VID_EMPRESTIMO, VID_USUARIO, VID_LIVRO;
			IF NOT FIM THEN
				INSERT INTO RELATORIO VALUES(NULL, P_DATA_DEVOLUCAO, VID_USUARIO, VID_LIVRO, VID_EMPRESTIMO);
			END IF;
		UNTIL FIM END REPEAT;
	CLOSE REG;
END
?

CREATE PROCEDURE ADD_MULTA(P_MOTIVO VARCHAR(100))
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VID_USUARIO, ID_LIVRO INT;
	DECLARE VVALOR DECIMAL(10,2);
	DECLARE VDATA_DEVOLUCAO DATETIME;
	
	DECLARE REG CURSOR FOR
		SELECT DATA_DEVOLUCAO, ID_USUARIO, ID_LIVRO
		FROM RELATORIO;

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;
		REPEAT
			FETCH REG INTO VDATA_DEVOLUCAO, VID_USUARIO, VID_LIVRO;
			IF NOT FIM THEN
				IF NOW() > VDATA_DEVOLUCAO THEN
					SET VVALOR = VVALOR + 1
				END IF;

				INSERT INTO MULTA VALUES(NULL, VVALOR, P_MOTIVO, VID_USUARIO, VID_LIVRO);

			END IF;
		UNTIL FIM END REPEAT;
	CLOSE REG;			
END
?

DELIMITER ;

-- EM ANDAMENTO
