DELIMITER /

CREATE PROCEDURE ADD_USUARIO(P_NOME VARCHAR(30), P_SOBRENOME VARCHAR(80), P_SEXO CHAR(1), P_CPF CHAR(11), P_EMAIL VARCHAR(80))
BEGIN
	INSERT INTO USUARIO VALUES(NULL, P_NOME, P_SOBRENOME, P_SEXO, P_CPF, P_EMAIL);
END
/

CREATE PROCEDURE ADD_ENDERECO(P_RUA VARCHAR(30), P_BAIRRO VARCHAR(30), P_CIDADE VARCHAR(30), P_ESTADO CHAR(2), P_ID_USUARIO INT)
BEGIN
	INSERT INTO ENDERECO VALUES(NULL, P_RUA, P_BAIRRO, P_CIDADE, P_ESTADO, P_ID_USUARIO);
END
/

CREATE PROCEDURE ADD_CONTATO(P_TIPO ENUM('COM', 'RES', 'CEL'), P_NUMERO CHAR(11), P_ID_USUARIO INT)
BEGIN
	INSERT INTO CONTATO VALUES(NULL, P_TIPO, P_NUMERO, P_ID_USUARIO);
END
/


CREATE PROCEDURE ADD_LIVRO(P_LIVRO VARCHAR(80), P_AUTOR VARCHAR(80))
BEGIN
	INSERT INTO ACERVO_LIVROS VALUES(NULL, P_LIVRO, P_AUTOR);
END
/

CREATE PROCEDURE ADD_USUARIO_LIVRO(P_ID_USUARIO INT, P_ID_LIVRO INT)
BEGIN
	INSERT INTO USUARIO_LIVRO VALUES(P_ID_USUARIO, P_ID_LIVRO);
END
/

CREATE PROCEDURE ADD_EMPRESTIMO_DEVOLUCAO(P_EMPRESTIMO CHAR(10), P_DEVOLUCAO CHAR(10), P_ID_USUARIO INT, P_ID_LIVRO INT)
BEGIN
	INSERT INTO EMPRESTIMO_DEVOLUCAO VALUES(NULL, P_EMPRESTIMO, P_DEVOLUCAO, P_ID_USUARIO, P_ID_LIVRO);
END
/

DELIMITER ;
