-- PROCEDURE

DELIMITER ?

CREATE PROCEDURE ADD_MULTA(IN P_MOTIVO VARCHAR(100))
BEGIN
    DECLARE FIM INT DEFAULT 0;
    DECLARE VID_USUARIO, VID_LIVRO INT;
    DECLARE VVALOR DECIMAL(10,2) DEFAULT 0;
    DECLARE VDATA_DEVOLUCAO DATETIME;

    DECLARE REG CURSOR FOR
        SELECT DATA_DEVOLUCAO, ID_USUARIO, ID_LIVRO
        FROM RELATORIO;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

    OPEN REG;

    REPEAT
        FETCH REG INTO VDATA_DEVOLUCAO, VID_USUARIO, VID_LIVRO;
        IF NOT FIM THEN
            IF NOW() > VDATA_DEVOLUCAO THEN
                SET VVALOR = VVALOR + 1;
                INSERT INTO MULTA (VALOR, MOTIVO, ID_USUARIO, ID_LIVRO) 
                VALUES (VVALOR, P_MOTIVO, VID_USUARIO, VID_LIVRO);
            ELSE
                SELECT DISTINCT "A multa ainda não pode ser inserida";
            END IF;
        END IF;
    UNTIL FIM END REPEAT;

    CLOSE REG;
END
?

DELIMITER ;

-- PROJETO EM ANDAMENTO PARA ATUALIZAÇÕES E NOVAS PROCEDURES
