-- TRIGGERS

DELIMITER ?

CREATE TRIGGER ADD_RELATORIO
AFTER INSERT ON EMPRESTIMO
FOR EACH ROW
BEGIN
	DECLARE VDATA_DEVOLUCAO DATETIME;
	
    SET VDATA_DEVOLUCAO = DATE_ADD(NEW.EMPRESTIMO, INTERVAL 7 DAY);

	INSERT INTO RELATORIO VALUES(NULL, VDATA_DEVOLUCAO, NEW.ID_USUARIO, NEW.ID_LIVRO, NEW.IDEMPRESTIMO);
END
?

DELIMITER ;
